config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_goal.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

my_goal/urls.py
from django.urls import path
from . import views

app_name = 'my_goal'
urlpatterns = [
    path('',views.IndexView.as_view(), name="index"),

    path('my_goal-create/',views.My_GoalCreateView.as_view(), name="goal_create"),
    path('my_goal-delete/<int:pk>',views.My_GoalDeleteView.as_view(), name="goal_delete"),
    path('my_goal-detail/<int:pk>',views.My_GoalDetailView.as_view(), name="goal_detail"),
    path('my_goal-list/',views.My_GoalListView.as_view(), name="goal_list"),
    path('my_goal-update/<int:pk>',views.My_GoalUpdateView.as_view(), name="goal_update"),
    
]

accounts/models.py
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    class Meta:
        verbose_name_plural='CustomUser'

my_goal/models.py
from tabnanny import verbose
from django.db import models


# Create your models here.

class My_Goal(models.Model):
    '''目標モデル'''

    
    title=models.CharField(verbose_name='目標',max_length=40)
    content=models.TextField(verbose_name='振り返り',blank=True,null=True)
    created_at=models.DateField(verbose_name='作成日時',auto_now_add=True)
    updated_at=models.DateField(verbose_name='更新日時',auto_now=True)

    class Meta:
        verbose_name_plural='Goal'

        def __str__(self):
            return self.title

my_goal/forms.py
from .models import My_Goal
from django import forms

class My_GoalCreateForm(forms.ModelForm):
    class Meta:
        model=My_Goal
        fields = ('title', 'content')
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render

# Create your views here.

my_goal/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from .models import My_Goal
from .forms import My_GoalCreateForm 

# Create your views here.

class IndexView(generic.TemplateView):
    template_name = "index.html"

class My_GoalCreateView(LoginRequiredMixin,generic.CreateView):
    model = My_Goal
    template_name = 'my_goal_create.html'
    form_class = My_GoalCreateForm
    success_url = reverse_lazy('my_goal:my_goal_list')

    def form_valid(self, form):
        my_goal = form.save(commit=False)
        my_goal.user = self.request.user
        my_goal.save()
        messages.success(self.request, '日記を作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "日記の作成に失敗しました。")
        return super().form_invalid(form)

# 日記編集
class My_GoalUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = My_Goal
    template_name = 'goal_update.html'
    form_class = My_GoalCreateForm

    def get_success_url(self):
        return reverse_lazy('my_goal:my_goal_detail', kwargs={'pk':self.kwargs['pk']})
    
    # 成功したとき
    def form_valid(self, form):
        messages.success(self.request,'日記を更新しました。')
        return super().form_valid(form)
    
    # 失敗したとき
    def form_invalid(self, form):
        messages.error(self.request,'日記の更新に失敗しました。')
        return super().form_invalid(form)

#　リスト
class My_GoalListView(LoginRequiredMixin,generic.ListView):
    model = My_Goal
    template_name = 'goal_list.html'
    paginate_by = 3

    def get_queryset(self):
        goals = My_Goal.objects.filter(user=self.request.user).order_by('-created_at')
        return goals

class My_GoalDetailView(LoginRequiredMixin,generic.DetailView):
    model = My_Goal
    template_name = 'goal_detail.html'
    pk_url_kwarg = 'id'

# 日記削除
class My_GoalDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = My_Goal
    template_name = 'goal_delete.html'
    success_url = reverse_lazy('my_goal:goal_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "日記を削除しました。")
        return super().delete(request, *args, **kwargs)

my_goal/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/business-casual.css' %}" rel="stylesheet" />
        {%block head %}{% endblock %}
    </head>
    <body>
        <!-- Header-->
        {% block header %}{% endblock %}

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
            <div class="container">
                <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="{% url 'my_goal:index' %}">MyGoal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'my_goal:index' %}">Home</a></li>
                        <!-- <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="about.html">About</a></li> -->
                        <!-- <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="products.html">Products</a></li> -->
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'social:begin' 'google-oauth2' %}">login</a></li>

                        {% if user.is_authenticated %}
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'my_goal:goal_list' %}">Goal List</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Content -->
        {% block content %}{% endblock %}

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

my_goal/templates/goal_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}目標作成 | My_Gaoal{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">作成</button>
        </form>
    </div>
</div>
{% endblock %}

my_goal/templates/goal_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}目標削除 | My Goal{% endblock %}

{% block content %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST">
            {% csrf_token %}
            <p>本当に削除しますか？</p>
            <button class="btn btn-primary mt-5" type="submit">削除</button>
            <a class="btn btn-secondary mt-5 ml-2" href="{% url 'my_goal:my_goal_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

my_goal/templates/goal_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}目標一覧｜My Goal{% endblock %}

{% block active_goal_list %}active{% endblock %}

{% block head %}
<!-- css未定 -->
{% endblock %}

{% block contents %}
<div class='container px-4 px-lg-5 my-div-style'>
    <div class='row gx-4 gx-lg-5 justify-content-center'>
        <div class='col-md-10 col-lg-8 col-xl-7'>
            <div class='d-flex justify-content-end mb-4'>
                <a class='btn btn-primary float-right' href="{% url 'my_goal:goal_create' %}">新規作成</a>
            </div>
            {% for goal in goal_list %}
            <div class='post-preview'>
                <a href="{% url 'my_goal:goal_detail' goal.pk %}">
                    <h2 class='post-title'>
                        {{ goal.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ goal.content|truncatechars:20 }}
                    </h3>
                </a>
                <p class="post-meta">{{ goal.created_at }}</p>
            </div>
            <hr class="my-4">
            {% empty %}
            <p>目標がありません。</p>
            {% endfor %} 

            <!-- ページネーション処理 -->
            {% if is_paginated %}
            <ul class='pagination'> 
                <!-- 前ページへのリンク -->
                {% if page_obj.has_previous %}
                <li class='page-item'>
                    <a class='page-link' href="?page={{ page_obj.previous_pagenumber }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %} 

                <!-- ページ数表示 -->
                {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
                {% endfor %} 

                <!-- 次ページへのリンク -->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %} 
        </div>
    </div>
</div>
{% endblock %}

my_goal/templates/goal_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}目標、振り返り編集 | My Goal{% endblock %}



{% block content %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST">
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">更新</button>
            <a class="btn btn-secondary ml-2" href="{% url 'my_goal:goal_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

my_goal/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Web上にあなた専用の目標ページを保存できるサービス｜My Goal{% endblock %}

<!-- Header-->
{% block header %}
<header>
    <h1 class="site-heading text-center text-faded d-none d-lg-block">
        <span class="site-heading-upper text-primary mb-3">A Free Bootstrap Business Theme</span>
        <span class="site-heading-lower">Business Casual</span>
    </h1>
</header>
{% endblock %}

<!-- Content -->
{% block content %}
<section class="page-section clearfix">
    <div class="container">
        <div class="intro">
            <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'assets/img/intro.jpg' %}" alt="..." />
            <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                <h2 class="section-heading mb-4">
                    <span class="section-heading-upper">Fresh Coffee</span>
                    <span class="section-heading-lower">Worth Drinking</span>
                </h2>
                <p class="mb-3">Every cup of our quality artisan coffee starts with locally sourced, hand picked ingredients. Once you try it, our coffee will be a blissful addition to your everyday morning routine - we guarantee it!</p>
                <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="#!">Visit Us Today!</a></div>
            </div>
        </div>
    </div>
</section>
<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner bg-faded text-center rounded">
                    <h2 class="section-heading mb-4">
                        <span class="section-heading-upper">Our Promise</span>
                        <span class="section-heading-lower">To You</span>
                    </h2>
                    <p class="mb-0">When you walk into our shop to start your day, we are dedicated to providing you with friendly service, a welcoming atmosphere, and above all else, excellent products made with the highest quality ingredients. If you are not satisfied, please let us know and we will do whatever we can to make things right!</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}